
import jwt from 'jsonwebtoken';

const SECRET = "dev-secret-key-123";
// Replace with the token generated by gen_token.py (I'll need to capture it fully)
const token = process.argv[2];

if (!token) {
    console.error("Please provide a token as an argument");
    process.exit(1);
}

try {
    const decoded = jwt.verify(token, SECRET);
    console.log("SUCCESS: Decoded payload =", decoded);
} catch (e) {
    console.error("FAILURE: Verification failed =", e.message);
}
